package com.woniu.model;

public class Coordinate {
    @Override
	public String toString() {
		return "Coordinate [cooid=" + cooid + ", longitude=" + longitude + ", latitude=" + latitude + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinate.cooid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer cooid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinate.longitude
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinate.Latitude
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Double latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinate.cooid
     *
     * @return the value of coordinate.cooid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getCooid() {
        return cooid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinate.cooid
     *
     * @param cooid the value for coordinate.cooid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setCooid(Integer cooid) {
        this.cooid = cooid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinate.longitude
     *
     * @return the value of coordinate.longitude
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinate.longitude
     *
     * @param longitude the value for coordinate.longitude
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinate.Latitude
     *
     * @return the value of coordinate.Latitude
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinate.Latitude
     *
     * @param latitude the value for coordinate.Latitude
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
}