package com.woniu.model;

import java.util.Date;

public class Dealinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealinfo.infoid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealinfo.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer rtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealinfo.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealinfo.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealinfo.note
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealinfo.date
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealinfo.infoid
     *
     * @return the value of dealinfo.infoid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealinfo.infoid
     *
     * @param infoid the value for dealinfo.infoid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setInfoid(Integer infoid) {
        this.infoid = infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealinfo.rtid
     *
     * @return the value of dealinfo.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealinfo.rtid
     *
     * @param rtid the value for dealinfo.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setRtid(Integer rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealinfo.sid
     *
     * @return the value of dealinfo.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealinfo.sid
     *
     * @param sid the value for dealinfo.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealinfo.uid
     *
     * @return the value of dealinfo.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealinfo.uid
     *
     * @param uid the value for dealinfo.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealinfo.note
     *
     * @return the value of dealinfo.note
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealinfo.note
     *
     * @param note the value for dealinfo.note
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealinfo.date
     *
     * @return the value of dealinfo.date
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealinfo.date
     *
     * @param date the value for dealinfo.date
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
}