package com.woniu.model;

public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.pid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.district
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.street
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String street;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.pid
     *
     * @return the value of position.pid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.pid
     *
     * @param pid the value for position.pid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.district
     *
     * @return the value of position.district
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.district
     *
     * @param district the value for position.district
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.street
     *
     * @return the value of position.street
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.street
     *
     * @param street the value for position.street
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setStreet(String street) {
        this.street = street;
    }
}