package com.woniu.model;

public class Rtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtype.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer rtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtype.rtname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String rtname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rtype.rdis
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String rdis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtype.rtid
     *
     * @return the value of rtype.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtype.rtid
     *
     * @param rtid the value for rtype.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setRtid(Integer rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtype.rtname
     *
     * @return the value of rtype.rtname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getRtname() {
        return rtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtype.rtname
     *
     * @param rtname the value for rtype.rtname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setRtname(String rtname) {
        this.rtname = rtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rtype.rdis
     *
     * @return the value of rtype.rdis
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getRdis() {
        return rdis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rtype.rdis
     *
     * @param rdis the value for rtype.rdis
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setRdis(String rdis) {
        this.rdis = rdis;
    }
}