package com.woniu.model;

import java.util.Date;

public class Sirecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirecord.sirid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Integer sirid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirecord.siid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Integer siid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirecord.rtid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Integer rtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirecord.createtime
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirecord.count
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirecord.sirid
     *
     * @return the value of sirecord.sirid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Integer getSirid() {
        return sirid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirecord.sirid
     *
     * @param sirid the value for sirecord.sirid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setSirid(Integer sirid) {
        this.sirid = sirid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirecord.siid
     *
     * @return the value of sirecord.siid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Integer getSiid() {
        return siid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirecord.siid
     *
     * @param siid the value for sirecord.siid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setSiid(Integer siid) {
        this.siid = siid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirecord.rtid
     *
     * @return the value of sirecord.rtid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Integer getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirecord.rtid
     *
     * @param rtid the value for sirecord.rtid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setRtid(Integer rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirecord.createtime
     *
     * @return the value of sirecord.createtime
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirecord.createtime
     *
     * @param createtime the value for sirecord.createtime
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirecord.count
     *
     * @return the value of sirecord.count
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirecord.count
     *
     * @param count the value for sirecord.count
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}