package com.woniu.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SirecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public SirecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSiridIsNull() {
            addCriterion("sirid is null");
            return (Criteria) this;
        }

        public Criteria andSiridIsNotNull() {
            addCriterion("sirid is not null");
            return (Criteria) this;
        }

        public Criteria andSiridEqualTo(Integer value) {
            addCriterion("sirid =", value, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiridNotEqualTo(Integer value) {
            addCriterion("sirid <>", value, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiridGreaterThan(Integer value) {
            addCriterion("sirid >", value, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiridGreaterThanOrEqualTo(Integer value) {
            addCriterion("sirid >=", value, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiridLessThan(Integer value) {
            addCriterion("sirid <", value, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiridLessThanOrEqualTo(Integer value) {
            addCriterion("sirid <=", value, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiridIn(List<Integer> values) {
            addCriterion("sirid in", values, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiridNotIn(List<Integer> values) {
            addCriterion("sirid not in", values, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiridBetween(Integer value1, Integer value2) {
            addCriterion("sirid between", value1, value2, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiridNotBetween(Integer value1, Integer value2) {
            addCriterion("sirid not between", value1, value2, "sirid");
            return (Criteria) this;
        }

        public Criteria andSiidIsNull() {
            addCriterion("siid is null");
            return (Criteria) this;
        }

        public Criteria andSiidIsNotNull() {
            addCriterion("siid is not null");
            return (Criteria) this;
        }

        public Criteria andSiidEqualTo(Integer value) {
            addCriterion("siid =", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidNotEqualTo(Integer value) {
            addCriterion("siid <>", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidGreaterThan(Integer value) {
            addCriterion("siid >", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidGreaterThanOrEqualTo(Integer value) {
            addCriterion("siid >=", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidLessThan(Integer value) {
            addCriterion("siid <", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidLessThanOrEqualTo(Integer value) {
            addCriterion("siid <=", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidIn(List<Integer> values) {
            addCriterion("siid in", values, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidNotIn(List<Integer> values) {
            addCriterion("siid not in", values, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidBetween(Integer value1, Integer value2) {
            addCriterion("siid between", value1, value2, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidNotBetween(Integer value1, Integer value2) {
            addCriterion("siid not between", value1, value2, "siid");
            return (Criteria) this;
        }

        public Criteria andRtidIsNull() {
            addCriterion("rtid is null");
            return (Criteria) this;
        }

        public Criteria andRtidIsNotNull() {
            addCriterion("rtid is not null");
            return (Criteria) this;
        }

        public Criteria andRtidEqualTo(Integer value) {
            addCriterion("rtid =", value, "rtid");
            return (Criteria) this;
        }

        public Criteria andRtidNotEqualTo(Integer value) {
            addCriterion("rtid <>", value, "rtid");
            return (Criteria) this;
        }

        public Criteria andRtidGreaterThan(Integer value) {
            addCriterion("rtid >", value, "rtid");
            return (Criteria) this;
        }

        public Criteria andRtidGreaterThanOrEqualTo(Integer value) {
            addCriterion("rtid >=", value, "rtid");
            return (Criteria) this;
        }

        public Criteria andRtidLessThan(Integer value) {
            addCriterion("rtid <", value, "rtid");
            return (Criteria) this;
        }

        public Criteria andRtidLessThanOrEqualTo(Integer value) {
            addCriterion("rtid <=", value, "rtid");
            return (Criteria) this;
        }

        public Criteria andRtidIn(List<Integer> values) {
            addCriterion("rtid in", values, "rtid");
            return (Criteria) this;
        }

        public Criteria andRtidNotIn(List<Integer> values) {
            addCriterion("rtid not in", values, "rtid");
            return (Criteria) this;
        }

        public Criteria andRtidBetween(Integer value1, Integer value2) {
            addCriterion("rtid between", value1, value2, "rtid");
            return (Criteria) this;
        }

        public Criteria andRtidNotBetween(Integer value1, Integer value2) {
            addCriterion("rtid not between", value1, value2, "rtid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirecord
     *
     * @mbggenerated do_not_delete_during_merge Sat Jul 20 10:04:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}