package com.woniu.model;

public class Sistatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sistatus.ssid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer ssid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sistatus.siid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer siid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sistatus.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer rtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sistatus.count
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sistatus.ssid
     *
     * @return the value of sistatus.ssid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sistatus.ssid
     *
     * @param ssid the value for sistatus.ssid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSsid(Integer ssid) {
        this.ssid = ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sistatus.siid
     *
     * @return the value of sistatus.siid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getSiid() {
        return siid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sistatus.siid
     *
     * @param siid the value for sistatus.siid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSiid(Integer siid) {
        this.siid = siid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sistatus.rtid
     *
     * @return the value of sistatus.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sistatus.rtid
     *
     * @param rtid the value for sistatus.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setRtid(Integer rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sistatus.count
     *
     * @return the value of sistatus.count
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sistatus.count
     *
     * @param count the value for sistatus.count
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}