package com.woniu.model;

import java.util.List;

public class Site {
	
	
	public Position getPosition() {
		return position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public List<Sistatus> getSistatus() {
		return sistatus;
	}

	public void setSistatus(List<Sistatus> sistatus) {
		this.sistatus = sistatus;
	}

	private Position position;

	private List<Sistatus> sistatus; 
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.siid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer siid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.pid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.cooid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer cooid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.del
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.siname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String siname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.siid
     *
     * @return the value of site.siid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getSiid() {
        return siid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.siid
     *
     * @param siid the value for site.siid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSiid(Integer siid) {
        this.siid = siid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.pid
     *
     * @return the value of site.pid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.pid
     *
     * @param pid the value for site.pid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.cooid
     *
     * @return the value of site.cooid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getCooid() {
        return cooid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.cooid
     *
     * @param cooid the value for site.cooid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setCooid(Integer cooid) {
        this.cooid = cooid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.sid
     *
     * @return the value of site.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.sid
     *
     * @param sid the value for site.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.del
     *
     * @return the value of site.del
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.del
     *
     * @param del the value for site.del
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.siname
     *
     * @return the value of site.siname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getSiname() {
        return siname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.siname
     *
     * @param siname the value for site.siname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSiname(String siname) {
        this.siname = siname;
    }
}