package com.woniu.model;

import java.util.ArrayList;
import java.util.List;

public class SiteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public SiteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSiidIsNull() {
            addCriterion("siid is null");
            return (Criteria) this;
        }

        public Criteria andSiidIsNotNull() {
            addCriterion("siid is not null");
            return (Criteria) this;
        }

        public Criteria andSiidEqualTo(Integer value) {
            addCriterion("siid =", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidNotEqualTo(Integer value) {
            addCriterion("siid <>", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidGreaterThan(Integer value) {
            addCriterion("siid >", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidGreaterThanOrEqualTo(Integer value) {
            addCriterion("siid >=", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidLessThan(Integer value) {
            addCriterion("siid <", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidLessThanOrEqualTo(Integer value) {
            addCriterion("siid <=", value, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidIn(List<Integer> values) {
            addCriterion("siid in", values, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidNotIn(List<Integer> values) {
            addCriterion("siid not in", values, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidBetween(Integer value1, Integer value2) {
            addCriterion("siid between", value1, value2, "siid");
            return (Criteria) this;
        }

        public Criteria andSiidNotBetween(Integer value1, Integer value2) {
            addCriterion("siid not between", value1, value2, "siid");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andCooidIsNull() {
            addCriterion("cooid is null");
            return (Criteria) this;
        }

        public Criteria andCooidIsNotNull() {
            addCriterion("cooid is not null");
            return (Criteria) this;
        }

        public Criteria andCooidEqualTo(Integer value) {
            addCriterion("cooid =", value, "cooid");
            return (Criteria) this;
        }

        public Criteria andCooidNotEqualTo(Integer value) {
            addCriterion("cooid <>", value, "cooid");
            return (Criteria) this;
        }

        public Criteria andCooidGreaterThan(Integer value) {
            addCriterion("cooid >", value, "cooid");
            return (Criteria) this;
        }

        public Criteria andCooidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cooid >=", value, "cooid");
            return (Criteria) this;
        }

        public Criteria andCooidLessThan(Integer value) {
            addCriterion("cooid <", value, "cooid");
            return (Criteria) this;
        }

        public Criteria andCooidLessThanOrEqualTo(Integer value) {
            addCriterion("cooid <=", value, "cooid");
            return (Criteria) this;
        }

        public Criteria andCooidIn(List<Integer> values) {
            addCriterion("cooid in", values, "cooid");
            return (Criteria) this;
        }

        public Criteria andCooidNotIn(List<Integer> values) {
            addCriterion("cooid not in", values, "cooid");
            return (Criteria) this;
        }

        public Criteria andCooidBetween(Integer value1, Integer value2) {
            addCriterion("cooid between", value1, value2, "cooid");
            return (Criteria) this;
        }

        public Criteria andCooidNotBetween(Integer value1, Integer value2) {
            addCriterion("cooid not between", value1, value2, "cooid");
            return (Criteria) this;
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Integer value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Integer value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Integer value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Integer value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Integer value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Integer> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Integer> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Integer value1, Integer value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Integer value1, Integer value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andDelIsNull() {
            addCriterion("del is null");
            return (Criteria) this;
        }

        public Criteria andDelIsNotNull() {
            addCriterion("del is not null");
            return (Criteria) this;
        }

        public Criteria andDelEqualTo(Boolean value) {
            addCriterion("del =", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotEqualTo(Boolean value) {
            addCriterion("del <>", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThan(Boolean value) {
            addCriterion("del >", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("del >=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThan(Boolean value) {
            addCriterion("del <", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThanOrEqualTo(Boolean value) {
            addCriterion("del <=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelIn(List<Boolean> values) {
            addCriterion("del in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotIn(List<Boolean> values) {
            addCriterion("del not in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelBetween(Boolean value1, Boolean value2) {
            addCriterion("del between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("del not between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andSinameIsNull() {
            addCriterion("siname is null");
            return (Criteria) this;
        }

        public Criteria andSinameIsNotNull() {
            addCriterion("siname is not null");
            return (Criteria) this;
        }

        public Criteria andSinameEqualTo(String value) {
            addCriterion("siname =", value, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameNotEqualTo(String value) {
            addCriterion("siname <>", value, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameGreaterThan(String value) {
            addCriterion("siname >", value, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameGreaterThanOrEqualTo(String value) {
            addCriterion("siname >=", value, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameLessThan(String value) {
            addCriterion("siname <", value, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameLessThanOrEqualTo(String value) {
            addCriterion("siname <=", value, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameLike(String value) {
            addCriterion("siname like", value, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameNotLike(String value) {
            addCriterion("siname not like", value, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameIn(List<String> values) {
            addCriterion("siname in", values, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameNotIn(List<String> values) {
            addCriterion("siname not in", values, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameBetween(String value1, String value2) {
            addCriterion("siname between", value1, value2, "siname");
            return (Criteria) this;
        }

        public Criteria andSinameNotBetween(String value1, String value2) {
            addCriterion("siname not between", value1, value2, "siname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 17 14:45:57 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}