package com.woniu.model;

public class Station {
	public Position getPosition() {
		return position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	private User user;
	
	private Position position;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.pid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.cooid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer cooid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.sname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.del
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Boolean del;

	private Thread thread;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.sid
     *
     * @return the value of station.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.sid
     *
     * @param sid the value for station.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.uid
     *
     * @return the value of station.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.uid
     *
     * @param uid the value for station.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.pid
     *
     * @return the value of station.pid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.pid
     *
     * @param pid the value for station.pid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.cooid
     *
     * @return the value of station.cooid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getCooid() {
        return cooid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.cooid
     *
     * @param cooid the value for station.cooid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setCooid(Integer cooid) {
        this.cooid = cooid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.sname
     *
     * @return the value of station.sname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.sname
     *
     * @param sname the value for station.sname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.del
     *
     * @return the value of station.del
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.del
     *
     * @param del the value for station.del
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setDel(Boolean del) {
        this.del = del;
    }
}