package com.woniu.model;

import java.util.Date;

public class Strecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strecord.srid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Integer srid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strecord.sid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strecord.rtid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Integer rtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strecord.createtime
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strecord.count
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strecord.srid
     *
     * @return the value of strecord.srid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Integer getSrid() {
        return srid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strecord.srid
     *
     * @param srid the value for strecord.srid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setSrid(Integer srid) {
        this.srid = srid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strecord.sid
     *
     * @return the value of strecord.sid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strecord.sid
     *
     * @param sid the value for strecord.sid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strecord.rtid
     *
     * @return the value of strecord.rtid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Integer getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strecord.rtid
     *
     * @param rtid the value for strecord.rtid
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setRtid(Integer rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strecord.createtime
     *
     * @return the value of strecord.createtime
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strecord.createtime
     *
     * @param createtime the value for strecord.createtime
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strecord.count
     *
     * @return the value of strecord.count
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strecord.count
     *
     * @param count the value for strecord.count
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}