package com.woniu.model;

public class Ststatus {
    public Ststatus() {
		super();
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ststatus.stid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer stid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ststatus.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer rtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ststatus.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ststatus.count
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ststatus.stid
     *
     * @return the value of ststatus.stid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ststatus.stid
     *
     * @param stid the value for ststatus.stid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setStid(Integer stid) {
        this.stid = stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ststatus.rtid
     *
     * @return the value of ststatus.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ststatus.rtid
     *
     * @param rtid the value for ststatus.rtid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setRtid(Integer rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ststatus.sid
     *
     * @return the value of ststatus.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ststatus.sid
     *
     * @param sid the value for ststatus.sid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ststatus.count
     *
     * @return the value of ststatus.count
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ststatus.count
     *
     * @param count the value for ststatus.count
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}