package com.woniu.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.did
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hirdate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Date hirdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.unum
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer unum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upwd
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String upwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salary
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Double salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.del
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Boolean del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.did
     *
     * @return the value of user.did
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.did
     *
     * @param did the value for user.did
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hirdate
     *
     * @return the value of user.hirdate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Date getHirdate() {
        return hirdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hirdate
     *
     * @param hirdate the value for user.hirdate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setHirdate(Date hirdate) {
        this.hirdate = hirdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.unum
     *
     * @return the value of user.unum
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getUnum() {
        return unum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.unum
     *
     * @param unum the value for user.unum
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setUnum(Integer unum) {
        this.unum = unum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upwd
     *
     * @return the value of user.upwd
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upwd
     *
     * @param upwd the value for user.upwd
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.salary
     *
     * @return the value of user.salary
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.salary
     *
     * @param salary the value for user.salary
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.del
     *
     * @return the value of user.del
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.del
     *
     * @param del the value for user.del
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setDel(Boolean del) {
        this.del = del;
    }
}