package com.woniu.model;

public class UserroleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.rid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.rid
     *
     * @return the value of userrole.rid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.rid
     *
     * @param rid the value for userrole.rid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.uid
     *
     * @return the value of userrole.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.uid
     *
     * @param uid the value for userrole.uid
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid;
    }
}