package com.woniu.model;

import java.util.Date;

public class Vrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vrecord.vrid
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    private Integer vrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vrecord.vid
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    private Integer vid;
    
    private Integer rtid;//承运垃圾类型id
    
    private String rtname;//承运垃圾类型名称
    
    private Integer sid;//所属站点id
    
    private String sname;//所属站点名称
    
    private String uname;//司机姓名
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vrecord.uid
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vrecord.starttime
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vrecord.endtime
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vrecord.note
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vrecord.count
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vrecord.vrid
     *
     * @return the value of vrecord.vrid
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public Integer getVrid() {
        return vrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vrecord.vrid
     *
     * @param vrid the value for vrecord.vrid
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public void setVrid(Integer vrid) {
        this.vrid = vrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vrecord.vid
     *
     * @return the value of vrecord.vid
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vrecord.vid
     *
     * @param vid the value for vrecord.vid
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vrecord.uid
     *
     * @return the value of vrecord.uid
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vrecord.uid
     *
     * @param uid the value for vrecord.uid
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vrecord.starttime
     *
     * @return the value of vrecord.starttime
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vrecord.starttime
     *
     * @param starttime the value for vrecord.starttime
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vrecord.endtime
     *
     * @return the value of vrecord.endtime
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vrecord.endtime
     *
     * @param endtime the value for vrecord.endtime
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vrecord.note
     *
     * @return the value of vrecord.note
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vrecord.note
     *
     * @param note the value for vrecord.note
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vrecord.count
     *
     * @return the value of vrecord.count
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vrecord.count
     *
     * @param count the value for vrecord.count
     *
     * @mbggenerated Mon Jul 22 16:08:19 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

	public Integer getRtid() {
		return rtid;
	}

	public void setRtid(Integer rtid) {
		this.rtid = rtid;
	}

	public String getRtname() {
		return rtname;
	}

	public void setRtname(String rtname) {
		this.rtname = rtname;
	}

	public Integer getSid() {
		return sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getSname() {
		return sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}
}