package com.woniu.mapper;

import com.woniu.model.Coordinate;
import com.woniu.model.CoordinateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoordinateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int countByExample(CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByExample(CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByPrimaryKey(Integer cooid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insert(Coordinate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insertSelective(Coordinate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    List<Coordinate> selectByExample(CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    Coordinate selectByPrimaryKey(Integer cooid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Coordinate record, @Param("example") CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExample(@Param("record") Coordinate record, @Param("example") CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKeySelective(Coordinate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKey(Coordinate record);
}