package com.woniu.mapper;

import com.woniu.model.Rtype;
import com.woniu.model.RtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int countByExample(RtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByExample(RtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByPrimaryKey(Integer rtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insert(Rtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insertSelective(Rtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    List<Rtype> selectByExample(RtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    Rtype selectByPrimaryKey(Integer rtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Rtype record, @Param("example") RtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExample(@Param("record") Rtype record, @Param("example") RtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKeySelective(Rtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtype
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKey(Rtype record);
}