package com.woniu.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.woniu.model.Rtype;
import com.woniu.model.Sirecord;
import com.woniu.model.SirecordExample;

public interface SirecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int countByExample(SirecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int deleteByExample(SirecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int deleteByPrimaryKey(Integer sirid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int insert(Sirecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int insertSelective(Sirecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    List<Sirecord> selectByExample(SirecordExample example);
    
    /**
     * This method was generated by Shen.
     * This method corresponds to the database table sirecord
     * 该方法旨在把多条同站点同时间的不同类型的多条记录合并成一条记录，直接用行转列的SQL查询语句获取单条的查询结果，返回值为HashMap类型
	 * resultType指出查询结果是用HashMap接受的每一条结果，查出的多条记录的类型体现在Mapper的返回值处，需要用HashMap泛型的List接收
     * @shengenerated Mon Jul 22 17:18:25 CST 2019
     */
    List<HashMap<?,?>> selectBySite(@Param("rtypes") List<Rtype> rtypes);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    Sirecord selectByPrimaryKey(Integer sirid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Sirecord record, @Param("example") SirecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByExample(@Param("record") Sirecord record, @Param("example") SirecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByPrimaryKeySelective(Sirecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByPrimaryKey(Sirecord record);
}