package com.woniu.mapper;

import com.woniu.model.Sirecord;
import com.woniu.model.SirecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int countByExample(SirecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int deleteByExample(SirecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int deleteByPrimaryKey(Integer sirid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int insert(Sirecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int insertSelective(Sirecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    List<Sirecord> selectByExample(SirecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    Sirecord selectByPrimaryKey(Integer sirid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Sirecord record, @Param("example") SirecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByExample(@Param("record") Sirecord record, @Param("example") SirecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByPrimaryKeySelective(Sirecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByPrimaryKey(Sirecord record);
}