package com.woniu.mapper;

import com.woniu.model.Sistatus;
import com.woniu.model.SistatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SistatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int countByExample(SistatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByExample(SistatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insert(Sistatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insertSelective(Sistatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    List<Sistatus> selectByExample(SistatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    Sistatus selectByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Sistatus record, @Param("example") SistatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExample(@Param("record") Sistatus record, @Param("example") SistatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKeySelective(Sistatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sistatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKey(Sistatus record);
}