package com.woniu.mapper;

import com.woniu.model.Site;
import com.woniu.model.SiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int countByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByPrimaryKey(Integer siid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insert(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insertSelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    List<Site> selectByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    Site selectByPrimaryKey(Integer siid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Site record, @Param("example") SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExample(@Param("record") Site record, @Param("example") SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKeySelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKey(Site record);
}