package com.woniu.mapper;

import com.woniu.model.Strecord;
import com.woniu.model.StrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int countByExample(StrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int deleteByExample(StrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int deleteByPrimaryKey(Integer srid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int insert(Strecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int insertSelective(Strecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    List<Strecord> selectByExample(StrecordExample example);
    
    /**
     * 添加了根据站点和时间去重查询的方法
     * This method was generated by Shen.
     * This method corresponds to the database table strecord
     *
     * @shengenerated Sat Jul 21 04:47:52 CST 2019
     */
    List<Strecord> selectByStation();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    Strecord selectByPrimaryKey(Integer srid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Strecord record, @Param("example") StrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByExample(@Param("record") Strecord record, @Param("example") StrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByPrimaryKeySelective(Strecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strecord
     *
     * @mbggenerated Sat Jul 20 10:04:21 CST 2019
     */
    int updateByPrimaryKey(Strecord record);
}