package com.woniu.mapper;

import com.woniu.model.Ststatus;
import com.woniu.model.StstatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int countByExample(StstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByExample(StstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByPrimaryKey(Integer stid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insert(Ststatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insertSelective(Ststatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    List<Ststatus> selectByExample(StstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    Ststatus selectByPrimaryKey(Integer stid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Ststatus record, @Param("example") StstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExample(@Param("record") Ststatus record, @Param("example") StstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKeySelective(Ststatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ststatus
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKey(Ststatus record);
    
    List<Ststatus> selectBySid(Integer sid);//根据sid查当前站点的状态集合
}