package com.woniu.mapper;

import com.woniu.model.Vehicles;
import com.woniu.model.VehiclesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VehiclesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int countByExample(VehiclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByExample(VehiclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insert(Vehicles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insertSelective(Vehicles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    List<Vehicles> selectByExample(VehiclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    Vehicles selectByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Vehicles record, @Param("example") VehiclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExample(@Param("record") Vehicles record, @Param("example") VehiclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKeySelective(Vehicles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicles
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKey(Vehicles record);
    
    List<Vehicles> selectBySid(Integer sid);//根据sid找车
}