package com.woniu.mapper;

import com.woniu.model.Vrecord;
import com.woniu.model.VrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int countByExample(VrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByExample(VrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int deleteByPrimaryKey(Integer vrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insert(Vrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int insertSelective(Vrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    List<Vrecord> selectByExample(VrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    Vrecord selectByPrimaryKey(Integer vrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Vrecord record, @Param("example") VrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByExample(@Param("record") Vrecord record, @Param("example") VrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKeySelective(Vrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vrecord
     *
     * @mbggenerated Wed Jul 17 14:45:57 CST 2019
     */
    int updateByPrimaryKey(Vrecord record);
}