server:
  port: 8099
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tree?serverTimezone=Asia/Shanghai
    username: root
    password: 
    
  mvc:
    view:
      prefix: /
      suffix: .jsp
      
logging:
  level:
    com: 
      woniu: 
        mapper: DEBUG    
        
      